name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: lazac-${{ matrix.os }}
          path: build/lazac

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/lazac-ubuntu-latest
            artifacts/lazac-macos-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
